from __future__ import annotations

APP_TITLE = "AeroMind Control Center"

HUD_EDGE_MARGIN = 32
HUD_TOP_MARGIN = 18
HUD_BOTTOM_MARGIN = 34
HUD_STACK_SPACING = 18
HUD_PANEL_RADIUS = 12
HUD_CHIP_RADIUS = 9
HUD_BUTTON_RADIUS = 8

STREAM_STATUS_LIVE = "Live"
STREAM_STATUS_CONNECTING = "Connecting"
STREAM_STATUS_RECONNECTING = "Reconnecting"
STREAM_STATUS_NO_SIGNAL = "No Signal"
STREAM_STATUS_STOPPED = "Stopped"

GESTURE_STATUS_ON = "GESTURE ON"
GESTURE_STATUS_OFF = "GESTURE OFF"
GESTURE_DETECTOR_READY = "Detector: READY"
GESTURE_DETECTOR_OFFLINE = "Detector: OFFLINE"
